name: 'Plugin Check'

on:
  pull_request:

jobs:
  plugin_check:
    runs-on: ubuntu-latest
    name: plugin check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: NoneBot2 Plugin Check
        uses: he0119/nonebot2-plugin-issue-bot@dev
        with:
          token: ${{ secrets.MYGITHUB_TOKEN }}
          base: main
          mode: check
